import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Sidebar from './components/SideBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Kade Greener',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-bub"></div>
        <div className="font-sans flex max-h-screen overflow-hidden">
          <Sidebar />
          <main className="flex flex-col gap-8 flex-1 row-start-2 items-center p-10 sm:items-start max-h-full overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
